sudo: false
language: python
python:
  - 2.7
  - 3.6
  - 3.7
  - 3.8
  - 3.9
matrix:
  include:
    - python: 3.9
    - dist: xenial
    - sudo: true
install:
  - pip install poetry
  - pipenv install -vvv
script:
  - poetry run coverage report -m
  - poetry run coverage run --source=api_appear -m pytest -v
after_success:
  - pipenv run coveralls